depuracion: false
notificaciones: true
prefix: "-"
fragmentos: 2
estado: online
juego:
 tipo: STREAMING
 nombre:
  - "-help"
  - "ğŸ‘¥ Usuarios: {nearby.usuarios} | ğŸ Servidores: {nearby.servidores} | âœ¨ Shard: [{nearby.shard.id}/{nearby.shard.conteo}]"
 url: "https://twitch.tv/davidbsxdd"
 tiempo: 0.1